DhWeb/Controllers/AboutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DhWeb.Controllers
{
    public class AboutController : Controller
    {
        // GET: About
        public ActionResult Index()
        {
            return View();
        }
    }
}

DhWeb/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DhWeb.Models;

namespace DhWeb.Controllers
{
    public class LoginController : Controller
    {
        LoginViewmodel model = new LoginViewmodel();
        // GET: Login
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Index(string loginUsername, string loginPassword)
        {
            if (model.IsUserAdmin(loginUsername, loginPassword))
            {
                return RedirectToAction("Index","SiteOptions");
            }
            else {
                return RedirectToAction("Index", "Home");
            }
        }
    }
}

DhWeb/Controllers/ProjectsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DhWeb.Controllers
{
    public class ProjectsController : Controller
    {
        // GET: Projects
        public ActionResult Index()
        {
            return View();
        }
    }
}

DhWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/css/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
 
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="@Url.Action("Index","Home")" class="navbar-brand">Hem</a>
                <a href="@Url.Action("Index","Projects")" class="navbar-brand">Projekt</a>
                <a href="@Url.Action("Index","About")" class="navbar-brand">Om mig</a>
                @if (User.IsInRole("Admin"))
                {
                    <a href="@Url.Action("Index","SiteOptions")" class="navbar-brand" id="login-navbar">Logga in</a>
                }
               
                <div id="login-bar">
                    @using(Html.BeginForm("Index","Login"))
                    {
                        <input type="text" name="loginUsername" />
                        <input type="text" name="loginPassword" />
                        <input type="submit" name="loginButton" value="Logga in" /> 
                    }
                  
                </div>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Daniel Hedén</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>