DhWeb/Models/SiteOptions.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DhWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SiteOptions
    {
        public int Id { get; set; }
        public string ImageUrl { get; set; }
        public string mainPresentationText { get; set; }
    }
}

DhWeb/Controllers/SiteOptionsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DhWeb.Models;
using System.IO;

namespace DhWeb.Controllers
{
    public class SiteOptionsController : Controller
    {
        private adminDatabaseEntities db = new adminDatabaseEntities();
      

        // GET: SiteOptions
        public ActionResult Index()
        {
            return View(db.SiteOptions.ToList());
        }

        [ValidateAntiForgeryToken]
        [HttpPost]
        public ActionResult UploadFile(SiteOptions model)
        {

                HttpPostedFileBase postedFile = Request.Files[0] as HttpPostedFileBase;
                string baseUrl = "/Content/Uploaded/";
                if (postedFile.ContentLength > 0)
                {
                    //Sätt vilken adress det är till den folder som ska användas
                    string folderPath = Server.MapPath(baseUrl);
                    //Skapa foldern
                    Directory.CreateDirectory(folderPath);

                    //Koppla den skapade foldern med de nya filens namn för en url
                    string saveFileName = Server.MapPath(baseUrl + postedFile.FileName);

                    //Spara
                    postedFile.SaveAs(saveFileName);

                model.ImageUrl = baseUrl + postedFile.FileName;

                if (ModelState.IsValid)
                {
                    db.SiteOptions.Add(model);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
                else
                {
                    return Content("Invalid File"); 
                }

            return View();
        }
        // GET: SiteOptions/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SiteOptions siteOptions = db.SiteOptions.Find(id);
            if (siteOptions == null)
            {
                return HttpNotFound();
            }
            return View(siteOptions);
        }

        // GET: SiteOptions/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: SiteOptions/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Create([Bind(Include = "Id,ImageUrl")] SiteOptions siteOptions)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        db.SiteOptions.Add(siteOptions);
        //        db.SaveChanges();
        //        return RedirectToAction("Index");
        //    }

        //    return View(siteOptions);
        //}

        // GET: SiteOptions/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SiteOptions siteOptions = db.SiteOptions.Find(id);
            if (siteOptions == null)
            {
                return HttpNotFound();
            }
            return View(siteOptions);
        }

        // POST: SiteOptions/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,ImageUrl")] SiteOptions siteOptions)
        {
            if (ModelState.IsValid)
            {
                db.Entry(siteOptions).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(siteOptions);
        }

        // GET: SiteOptions/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SiteOptions siteOptions = db.SiteOptions.Find(id);
            if (siteOptions == null)
            {
                return HttpNotFound();
            }
            return View(siteOptions);
        }

        // POST: SiteOptions/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            SiteOptions siteOptions = db.SiteOptions.Find(id);
            db.SiteOptions.Remove(siteOptions);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

DhWeb/Views/SiteOptions/Create.cshtml
@model DhWeb.Models.SiteOptions

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm("UploadFile","SiteOptions", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>SiteOptions</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ImageUrl, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.EditorFor(model => model.ImageUrl, new { htmlAttributes = new { @class = "form-control" } })*@
                @Html.
                <input type="file" name="upload-file"/>
                @Html.ValidationMessageFor(model => model.ImageUrl, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Upload" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

DhWeb/Views/SiteOptions/Delete.cshtml
@model DhWeb.Models.SiteOptions

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>SiteOptions</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ImageUrl)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ImageUrl)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

DhWeb/Views/SiteOptions/Details.cshtml
@model DhWeb.Models.SiteOptions

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>SiteOptions</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ImageUrl)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ImageUrl)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

DhWeb/Views/SiteOptions/Edit.cshtml
@model DhWeb.Models.SiteOptions

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>SiteOptions</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.ImageUrl, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ImageUrl, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ImageUrl, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

DhWeb/Views/SiteOptions/Index.cshtml
@model IEnumerable<DhWeb.Models.SiteOptions>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.ImageUrl)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.ImageUrl)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>